version: '3.8'
services:
  backend:
    build: .
    container_name: fanatik-backend-prod
    ports:
      - "80:3000"
    env_file:
      - .env
    restart: always
    depends_on:
      - db
  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    container_name: fanatik-frontend-prod
    ports:
      - "81:3000"
    env_file:
      - ../../frontend/.env
    restart: always
    depends_on:
      - backend
  db:
    image: postgres:15-alpine
    container_name: fanatik-db-prod
    environment:
      POSTGRES_DB: fanatik_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
volumes:
  postgres_data_prod:
